// lib/copy.js
export const copy = {
  checkoutUrl: "https://www.oriopay.app/p/prirodna-kozmetika1",

  metadata: {
    title: "Vodič za prirodnu kozmetiku",
    description:
      "80 recepata za 100 % prirodnu kozmetiku koju možete napraviti kod kuće. Testirane i provjerene formule za sigurnu njegu kože i izbjegavanje toksičnih kemikalija.",
  },

  hero: {
    headlineLine1: "80 recepata za",
    headlineHighlight: "PRIRODNU KOZMETIKU",
    subheadline:
      "Dobijte pristup tajnim receptima za 100 % prirodnu kozmetiku koju možete izraditi u udobnosti vlastitog doma! Testirane i sigurne formule za zaštitu vaše obitelji i odustajanje od industrijskih proizvoda punih toksina.",
    cta: "ŽELIM PRISTUP ODMAH!",
    imageAlt: "Vodič za prirodnu kozmetiku",
    timerLabels: {
      days: "Dani",
      hours: "Sati",
      minutes: "Minute",
      seconds: "Sekunde",
    },
  },

  story: {
    text: "Sada ću vam dati praktičan vodič, direktan i bez nepotrebnih komplikacija, ali iznimno pouzdan, kako biste kod kuće mogli izrađivati svoju 100 % prirodnu kozmetiku. Bez trošenja bogatstva, bez ovisnosti o tisućama sastojaka – i uz radost što je izrađujete za sebe, poklanjate voljenima i svi zajedno uživate u zdravoj i 100 % sigurnoj njezi!",
    imageAlt: "Prirodna kozmetika",
  },

  recipeList: {
    headline: "Upoznajte se s",
    headlineHighlight: "80 recepata,",
    headlineSuffix: "kojima ćete dobiti pristup u Vodiču za prirodnu kozmetiku:",
    cta: "ŽELIM IH!",
    col1: [
      "Umirujuća krema za tijelo",
      "Krema za tijelo s pantenolom",
      "Osvježavajući losion za tijelo",
      "Soufflé krema za tijelo",
      "Maslac za tijelo s urukumom",
      "Kruti maslac za tijelo",
      "Ulje za tijelo",
      "Terapeutsko ulje za mrlje i strije",
      "Dvofazno ulje za tijelo",
      "Prirodni losion za preplanulost",
      "Tekući sapun za tijelo",
      "Gel za tuširanje",
      "Kruti sapun za tijelo sa SCI-jem",
      "Tradicionalni kruti sapun za tijelo",
      "Kremasti hidratantni sapun",
      "Piling sapun za tijelo (Soap Body Scrub)",
      "Piling za tijelo",
      "Piling za tijelo s bademovim brašnom",
      "Prirodni iluminator za tijelo",
      "Sprej za tijelo (Body Splash)",
      "Krema za lice s vitaminom C",
      "Krema za lice poslije sunčanja s lavandom",
      "Krema za lice s glinom",
      "Hidratantni losion za lice s jasminom",
      "Suho ulje za lice (Dry Oil)",
      "Tekući sapun za lice",
      "Pjena za čišćenje lica",
      "Serum za lice za suhu i osjetljivu kožu",
      "Serum za lice za masnu kožu",
      "Serum za područje oko očiju",
      "Tonik za lice za suhu i osjetljivu kožu",
      "Osvježavajući tonik za lice za masnu kožu",
      "Ulje za čišćenje lica (Cleansing Oil)",
      "Balzam za čišćenje lica (Cleansing Balm)",
      "Sapun s crvenom glinom – Detoksikacija i revitalizacija",
      "Nježni piling za lice",
      "Gel za lice sa salicilnom kiselinom",
      "Gel-maska za lice s hijaluronskom kiselinom",
      "Eliksir za lice od ruža",
      "Sprej za lice s aloe verom",
      "Maska za kovrčavu i valovitu kosu",
    ],
    col2: [
      "Maska za ravnu i blago valovitu kosu",
      "Kremasti regenerator",
      "Kruti regenerator za kovrčavu i valovitu kosu",
      "Kruti regenerator za blago valovitu i ravnu kosu",
      "Kruti šampon za kovrčavu i valovitu kosu",
      "Kruti šampon za ravnu i blago valovitu kosu",
      "Tekući šampon",
      "Kremasti šampon 2 u 1",
      "Dječji šampon",
      "Regenerator koji se ne ispira (Leave-In)",
      "Sprej za zaštitu od topline",
      "Ulje za kosu",
      "Gel za kosu",
      "Prirodna pomada za kosu",
      "Hidratantni završni sprej",
      "Piling za vlasište",
      "Tonik za rast kose",
      "Serum za ispucale vrhove",
      "Parfem za kosu",
      "Prirodni sapun za intimnu njegu",
      "Prirodni dječji sapun za tijelo",
      "Prirodni tekući parfem",
      "Prirodni kruti parfem",
      "Zubna pasta u obliku gela",
      "Vodica za ispiranje usta",
      "Dezodorans u spreju",
      "Mast od nevena",
      "Mast od arnike",
      "Hranjivi balzam za usne",
      "Prirodni ruž za usne",
      "Prirodni piling za usne",
      "Sprej za skidanje šminke",
      "Pjena za brijanje",
      "Prirodni losion poslije brijanja",
      "Krema za ruke i stopala",
      "Gel za fiksiranje obrva",
      "Prirodna svijeća za masažu",
      "Hranjivi serum za nokte i zanoktice",
      "Prirodni repelent",
      "Revitalizirajuće soli za kupku",
    ],
  },

  whatYouGet: {
    headline: "ŠTO ĆETE PRONAĆI U OVOM IZVANREDNOM PRIRUČNIKU?",
    cta: "PREUZMITE VODIČ ODMAH!",
    imageAlt: "Što ćete pronaći u vodiču",
    items: [
      "Više od 80 testiranih i provjerenih recepata – uključujući kremasti piling sapun, suho ulje za lice, sprej za tijelo, zaštitu od topline za kosu i razne nove, inovativne formule.",
      "Baze za kreme, gelove, šampone i sapune – naučite stvarati potpuno sigurne i personalizirane formule za svaki tip kože i kose.",
      "Potpuni vodič korak po korak za početnike i napredne – savladajte sve, od osnovnih koncepata do najsloženijih kozmetičkih tehnika.",
      "Katalog sastojaka – otkrijte prednosti raznih prirodnih sirovina kako biste kreirali visokoučinkovitu i čistu kozmetiku.",
      "Fitoterapija primijenjena u kozmetologiji – kako maksimalno koristiti ljekovito bilje za pojačavanje djelovanja vaše kozmetike.",
      "Tajne prirodnog formuliranja – regulacija pH vrijednosti, prirodno konzerviranje, odabir sirovina i najučinkovitije sinergije.",
      "Savjeti za savršenu kućnu proizvodnju – pretvorite svoju kuhinju u sigurno mjesto za stvaranje čiste kozmetike i usavršite svoje tehnike.",
      "Održivost i briga za okoliš – naučite kreirati potpuno biorazgradivu kozmetiku koja je nježna prema planetu.",
    ],
  },

  testimonials: {
    headline: "POGLEDAJTE ŠTO KAŽU ŽENE KOJE VEĆ KORISTE OVAJ VODIČ:",
    cta: "ŽELIM PRISTUP ODMAH!",
    cards: [
      {
        name: "Ana M.",
        initials: "AM",
        color: "#16a34a",
        stars: 5,
        text: "Obožavam ovaj vodič! Već sam napravila umirujuću kremu za tijelo i sapun za lice, ispali su nevjerojatno. Puno su bolji od industrijskih proizvoda koje sam prije koristila. Topla preporuka svima!",
        source: "WhatsApp",
      },
      {
        name: "Jelena K.",
        initials: "JK",
        color: "#0f766e",
        stars: 5,
        text: "Cure, kakav predivan vodič! Recepti su vrlo detaljni i laki za praćenje. Već sam izradila nekoliko proizvoda za prijateljice i one ih obožavaju. Vrijedi svakog centa!",
        source: "WhatsApp",
      },
      {
        name: "Silvija R.",
        initials: "SR",
        color: "#7c3aed",
        stars: 5,
        text: "Bojala sam se kupiti ga, ali se itekako isplatilo! Katalog sirovina mi je jako pomogao da razumijem sastojke. Već sam isprobala 6 različitih recepata i svi su ispali besprijekorno.",
        source: "WhatsApp",
      },
      {
        name: "Ivana B.",
        initials: "IB",
        color: "#b45309",
        stars: 5,
        text: "Kakva nevjerojatna investicija! Pomoću vodiča sam napokon naučila raditi kruti šampon i regenerator. Kosa mi je oživjela, puno je zdravija, a štedim dosta novca svaki mjesec na kozmetici. Hvala vam!",
        source: "WhatsApp",
      },
    ],
  },

  autonomyIntro: {
    text1: "S Vodičem za prirodnu kozmetiku naučit ćete stvarati vlastite proizvode potpuno od nule.",
    text2: "Pokazat će vam korak po korak kako svjesno odabrati prirodne sastojke, prilagoditi formule različitim tipovima kože i poroznosti kose te personalizirati proizvode tako da savršeno odgovaraju vašim potrebama.",
    text3: "Steći ćete samopouzdanje i potpunu neovisnost u formuliranju. Moći ćete testirati i usavršavati recepte, kreirajući unikatnu kozmetiku s vlastitim karakterom. Zahvaljujući vrlo detaljnom katalogu prirodnih sirovina, upoznat ćete najbolje sastojke i otkriti idealne kombinacije za svaki tip proizvoda.",
    cta: "PREUZMITE VODIČ ODMAH!",
    imageAlt: "Neovisnost u izradi prirodne kozmetike",
  },

  benefitsList: {
    headline: "Neovisnost i kreativnost u svijetu prirodne njege!",
    cta: "ŽELIM PRISTUP ODMAH!",
    items: [
      {
        bold: "Naučite stvarati",
        rest: " kreme, serume, šampone, sapune i još mnogo drugih proizvoda za njegu.",
      },
      {
        bold: "Otkrijte kako bez greške odabrati",
        rest: " prave sastojke za svaku specifičnu potrebu kože i kose.",
      },
      {
        bold: "Oslobodite se industrijske kemije i",
        rest: " razvijte 100 % personalizirane, prirodne formule.",
      },
      {
        bold: "Uronite u fitoterapiju primijenjenu u kozmetologiji,",
        rest: " crpeći punim rukama ljekovita svojstva biljaka i ekstrakata.",
      },
      {
        bold: "Značajno smanjite troškove",
        rest: " stvarajući vlastitu kozmetiku bez i najmanjeg kompromisa u njezinoj kvaliteti.",
      },
      {
        bold: "Dobijte pristup profesionalnim formulama",
        rest: " i naučite kako sigurno izraditi proizvode najviše klase.",
      },
      {
        bold: "Pružite svojoj koži najbolju njegu,",
        rest: " točno znajući koje čiste sastojke koristite.",
      },
      {
        bold: "Zaštitite zdravlje svoje obitelji",
        rest: " proizvodima bez štetnih konzervansa i umjetnih boja.",
      },
    ],
  },

  economy: {
    headline: "Ušteda i zdrava njega bez ijednog grama kemije!",
    text1: "Stvaranje vlastite prirodne kozmetike najbolji je način za zaštitu kože, uz istovremenu ogromnu uštedu novca. S Vodičem za prirodnu kozmetiku naučit ćete kako proizvesti visokokvalitetne proizvode za djelić cijene onih iz drogerija. Tako ćete izbjeći preplaćivanje komercijalne kozmetike pune kemije, ulažući u pristupačne, čiste i visoko učinkovite prirodne sirovine.",
    text2: "Ovo je vaš neprocjenjiv priručnik za prijelaz na zdraviji stil života. Zahvaljujući ekskluzivnim receptima, vratit ćete potpunu kontrolu nad onim što nanosite na svoje tijelo. Možete uživati u ručno rađenim proizvodima koji su 100 % sigurni, ekološki i nježni kako za vašu kožu, tako i za okoliš.",
    cta: "POČINJEM IZRAĐIVATI!",
    imageAlt: "Zdrava njega",
  },

  finalCta: {
    urgencyLabel: "POSLJEDNJI DAN ZA NARUDŽBU",
    urgencySub: "po promotivnoj akcijskoj cijeni!",
    urgencyText:
      "Ovo je vaša apsolutno posljednja prilika da iskoristite našu iznimnu ponudu i pridružite se skupini od tisuća oduševljenih polaznica!",
    offerPrice: "8.90 €",
    button: "OSTVARITE PRISTUP ODMAH!",
    productTitle: "Vodič za prirodnu kozmetiku!",
    imageAlt: "Vodič za prirodnu kozmetiku",
    bundleList: [
      "80 recepata za prirodnu kozmetiku",
      "Sveobuhvatan priručnik korak po korak",
      "Edukativni leksikon sirovina",
      "Pristup zatvorenoj zajednici",
      "Stručna podrška za sva pitanja",
      "Provjeren i pouzdan popis dobavljača",
    ],
    timerLabels: {
      days: "Dani",
      hours: "Sati",
      minutes: "Minute",
      seconds: "Sekunde",
    },
  },

  footer: {
    tagline: "Otkrijte s nama kako stvoriti savršenu prirodnu kozmetiku!",
  },
};