// lib/copy.js
export const copy = {
  checkoutUrl: "https://www.oriopay.app/p/prirodna-kozmetika1",

  metadata: {
    title: "Vodič za prirodnu kozmetiku | PerfuMaria das Ervas",
    description:
      "80 recepata za 100 % prirodnu kozmetiku koju možete napraviti kod kuće. Testirane i provjerene formule za osobnu upotrebu ili pokretanje posla.",
  },

  hero: {
    headlineLine1: "80 recepata za",
    headlineHighlight: "PRIRODNU KOZMETIKU",
    subheadline:
      "Dobijte pristup tajnim receptima za 100 % prirodnu kozmetiku koju možete izraditi u udobnosti vlastitog doma! Testirane i provjerene formule za osobnu upotrebu ili za pokretanje vlastitog posla.",
    cta: "ŽELIM PRISTUP ODMAH!",
    imageAlt: "Vodič za prirodnu kozmetiku",
    timerLabels: {
      days: "Dani",
      hours: "Sati",
      minutes: "Minute",
      seconds: "Sekunde",
    },
  },

  story: {
    text: "Sada ću vam dati praktičan vodič, direktan i bez nepotrebnih komplikacija, ali iznimno pouzdan, kako biste kod kuće mogli izrađivati svoju 100 % prirodnu kozmetiku. Bez trošenja bogatstva, bez ovisnosti o tisućama sastojaka – i s mogućnošću da je koristite za sebe, poklonite voljenima ili čak prodajete ako želite stvoriti novi izvor prihoda!",
    imageAlt: "Prirodna kozmetika",
  },

  recipeList: {
    headline: "Upoznajte se s",
    headlineHighlight: "80 recepata,",
    headlineSuffix: "kojima ćete dobiti pristup u Vodiču za prirodnu kozmetiku:",
    cta: "ŽELIM IH!",
    col1: [
      "Umirujuća krema za tijelo",
      "Krema za tijelo s pantenolom",
      "Osvježavajući losion za tijelo",
      "Soufflé krema za tijelo",
      "Maslac za tijelo s urukumom",
      "Kruti maslac za tijelo",
      "Ulje za tijelo",
      "Terapeutsko ulje za mrlje i strije",
      "Dvofazno ulje za tijelo",
      "Prirodni losion za preplanulost",
      "Tekući sapun za tijelo",
      "Gel za tuširanje",
      "Kruti sapun za tijelo sa SCI-jem",
      "Tradicionalni kruti sapun za tijelo",
      "Kremasti hidratantni sapun",
      "Piling sapun za tijelo (Soap Body Scrub)",
      "Piling za tijelo",
      "Piling za tijelo s bademovim brašnom",
      "Prirodni iluminator za tijelo",
      "Sprej za tijelo (Body Splash)",
      "Krema za lice s vitaminom C",
      "Krema za lice poslije sunčanja s lavandom",
      "Krema za lice s glinom",
      "Hidratantni losion za lice s jasminom",
      "Suho ulje za lice (Dry Oil)",
      "Tekući sapun za lice",
      "Pjena za čišćenje lica",
      "Serum za lice za suhu i osjetljivu kožu",
      "Serum za lice za masnu kožu",
      "Serum za područje oko očiju",
      "Tonik za lice za suhu i osjetljivu kožu",
      "Osvježavajući tonik za lice za masnu kožu",
      "Ulje za čišćenje lica (Cleansing Oil)",
      "Balzam za čišćenje lica (Cleansing Balm)",
      "Sapun s crvenom glinom – Detoksikacija i revitalizacija",
      "Nježni piling za lice",
      "Gel za lice sa salicilnom kiselinom",
      "Gel-maska za lice s hijaluronskom kiselinom",
      "Eliksir za lice od ruža",
      "Sprej za lice s aloe verom",
      "Maska za kovrčavu i valovitu kosu",
    ],
    col2: [
      "Maska za ravnu i blago valovitu kosu",
      "Kremasti regenerator",
      "Kruti regenerator za kovrčavu i valovitu kosu",
      "Kruti regenerator za blago valovitu i ravnu kosu",
      "Kruti šampon za kovrčavu i valovitu kosu",
      "Kruti šampon za ravnu i blago valovitu kosu",
      "Tekući šampon",
      "Kremasti šampon 2 u 1",
      "Dječji šampon",
      "Regenerator koji se ne ispira (Leave-In)",
      "Sprej za zaštitu od topline",
      "Ulje za kosu",
      "Gel za kosu",
      "Prirodna pomada za kosu",
      "Hidratantni završni sprej",
      "Piling za vlasište",
      "Tonik za rast kose",
      "Serum za ispucale vrhove",
      "Parfem za kosu",
      "Prirodni sapun za intimnu njegu",
      "Prirodni dječji sapun za tijelo",
      "Prirodni tekući parfem",
      "Prirodni kruti parfem",
      "Zubna pasta u obliku gela",
      "Vodica za ispiranje usta",
      "Dezodorans u spreju",
      "Mast od nevena",
      "Mast od arnike",
      "Hranjivi balzam za usne",
      "Prirodni ruž za usne",
      "Prirodni piling za usne",
      "Sprej za skidanje šminke",
      "Pjena za brijanje",
      "Prirodni losion poslije brijanja",
      "Krema za ruke i stopala",
      "Gel za fiksiranje obrva",
      "Prirodna svijeća za masažu",
      "Hranjivi serum za nokte i zanoktice",
      "Prirodni repelent",
      "Revitalizirajuće soli za kupku",
    ],
  },

  whatYouGet: {
    headline: "ŠTO ĆETE PRONAĆI U OVOM SAVRŠENOM VODIČU?",
    cta: "PREUZMITE VODIČ ODMAH!",
    imageAlt: "Što ćete pronaći u vodiču",
    items: [
      "Više od 80 testiranih i provjerenih recepata – uključujući kremasti piling sapun, suho ulje za lice, sprej za tijelo, zaštitu od topline za kosu i razne nove formule.",
      "Baze za kreme, gelove, šampone i sapune – naučite stvarati sigurne i personalizirane formule za svaki tip kože i kose.",
      "Potpuni vodič korak po korak za početnike i napredne – savladajte sve, od osnovnih koncepata do najsloženijih tehnika.",
      "Katalog sastojaka – otkrijte prednosti raznih prirodnih sirovina kako biste kreirali visokoučinkovitu kozmetiku.",
      "Fitoterapija primijenjena u kozmetologiji – kako koristiti ljekovite biljke za pojačavanje djelovanja vaše kozmetike.",
      "Tajne prirodnog formuliranja – regulacija pH vrijednosti, konzerviranje, odabir sirovina i učinkovite kombinacije.",
      "Savjeti za kućnu i profesionalnu proizvodnju – stvorite vlastiti studio za prirodnu kozmetiku i usavršite svoje tehnike.",
      "Održivost i briga za okoliš – naučite kreirati biorazgradivu i ekološki prihvatljivu kozmetiku.",
    ],
  },

  testimonials: {
    headline: "POGLEDAJTE ŠTO DRUGI KAŽU O VODIČU ZA PRIRODNU KOZMETIKU:",
    cta: "ŽELIM PRISTUP ODMAH!",
    cards: [
      {
        name: "Ana M.",
        initials: "AM",
        color: "#16a34a",
        stars: 5,
        text: "Obožavam ovaj vodič! Već sam napravila umirujuću kremu za tijelo i sapun za lice, ispali su nevjerojatno. Puno su bolji od industrijskih proizvoda koje sam prije koristila. Topla preporuka!",
        source: "WhatsApp",
      },
      {
        name: "Jelena K.",
        initials: "JK",
        color: "#0f766e",
        stars: 5,
        text: "Ljudi, kakav predivan vodič! Recepti su vrlo detaljni i laki za praćenje. Već sam prodala nekoliko proizvoda prijateljicama i one ih obožavaju. Vrijedi svakog centa!",
        source: "WhatsApp",
      },
      {
        name: "Silvija R.",
        initials: "SR",
        color: "#7c3aed",
        stars: 5,
        text: "Bojala sam se kupiti ga, ali se itekako isplatilo! Katalog sirovina mi je jako pomogao da razumijem sastojke. Već sam isprobala 6 različitih recepata i svi su ispali odlično.",
        source: "WhatsApp",
      },
      {
        name: "Ivana B.",
        initials: "IB",
        color: "#b45309",
        stars: 5,
        text: "Kakva nevjerojatna investicija! Pomoću vodiča naučila sam raditi kruti šampon i regenerator. Kosa mi je puno zdravija i štedim dosta novca svaki mjesec. Hvala vam!",
        source: "WhatsApp",
      },
    ],
  },

  autonomyIntro: {
    text1: "S Vodičem za prirodnu kozmetiku naučit ćete stvarati svoju kozmetiku od nule.",
    text2: "Pokazat će vam korak po korak kako odabrati prirodne sastojke, prilagoditi formule različitim tipovima kože i kose te personalizirati proizvode prema vlastitim potrebama.",
    text3: "Osim toga, steći ćete samopouzdanje i neovisnost u formuliranju, s mogućnošću testiranja i prilagođavanja recepata kako biste stvorili jedinstvene proizvode s vlastitim potpisom. Zahvaljujući detaljnom katalogu prirodnih sirovina, upoznat ćete najbolje sastojke i naučiti idealne kombinacije za svaki kozmetički proizvod.",
    cta: "PREUZMITE VODIČ ODMAH!",
    imageAlt: "Neovisnost u prirodnoj kozmetici",
  },

  benefitsList: {
    headline: "Neovisnost i kreativnost u prirodnoj kozmetici!",
    cta: "ŽELIM PRISTUP ODMAH!",
    items: [
      {
        bold: "Naučite stvarati",
        rest: " kreme, serume, šampone, sapune i još mnogo toga.",
      },
      {
        bold: "Otkrijte kako odabrati",
        rest: " prave sastojke za svaku potrebu.",
      },
      {
        bold: "Postanite neovisni o industrijskoj kozmetici i",
        rest: " razvijte personalizirane formule.",
      },
      {
        bold: "Uronite u fitoterapiju primijenjenu u kozmetologiji,",
        rest: " koristeći terapeutska svojstva ljekovitih biljaka.",
      },
      {
        bold: "Smanjite troškove",
        rest: " stvarajući vlastitu kozmetiku bez kompromisa u kvaliteti.",
      },
      {
        bold: "Dobijte pristup profesionalnim formulama",
        rest: " i naučite kako sigurno izraditi najbolje proizvode.",
      },
      {
        bold: "Istaknite se na tržištu prirodne ljepote,",
        rest: " koje sve više raste i cijeni održive proizvode.",
      },
      {
        bold: "Naučite kako urediti kućni kozmetički studio,",
        rest: " uz praktične savjete za organizaciju radnog prostora.",
      },
    ],
  },

  economy: {
    headline: "Ušteda i poslovna prilika na prirodnom tržištu!",
    text1: "Stvaranje vlastite prirodne kozmetike odlična je prilika kako za uštedu, tako i za posao. S Vodičem za prirodnu kozmetiku naučit ćete kako proizvesti visokokvalitetnu kozmetiku po niskoj cijeni, izbjegavajući prekomjerne troškove konvencionalnih proizvoda i ulažući u pristupačne te učinkovite prirodne sastojke.",
    text2: "Ako želite pokrenuti vlastiti posao, ovo je dragocjen vodič za stvaranje održivog i isplativog poduhvata. Uz ekskluzivne formule i praktične savjete o konzerviranju, pakiranju i tržištu, možete stvoriti vlastiti brend prirodne kozmetike nudeći ručno rađene proizvode koji prate trend svjesne i ekološke potrošnje.",
    cta: "PREUZMITE VODIČ ODMAH!",
    imageAlt: "Poslovanje na prirodnom tržištu",
  },

  finalCta: {
    urgencyLabel: "POSLJEDNJI DAN ZA NARUDŽBU",
    urgencySub: "po promotivnoj cijeni!",
    urgencyText:
      "Ovo je vaša posljednja prilika da iskoristite našu posebnu ponudu i postanete dio naše obitelji s tisućama zadovoljnih polaznica!",
    offerPrice: "8.90 €",
    button: "OSTVARITE PRISTUP ODMAH!",
    productTitle: "Vodič za prirodnu kozmetiku!",
    imageAlt: "Vodič za prirodnu kozmetiku",
    bundleList: [
      "80 recepata za prirodnu kozmetiku",
      "Kompletan priručnik za učenje",
      "Edukativni katalog sirovina",
      "Zajednica polaznica",
      "Specijalizirana podrška za pitanja",
      "Popis dobavljača",
    ],
    timerLabels: {
      days: "Dani",
      hours: "Sati",
      minutes: "Minute",
      seconds: "Sekunde",
    },
  },

  footer: {
    tagline: "Otkrijte kako stvoriti savršenu prirodnu kozmetiku!",
    linkLabel: "Cjeloviti tečaj prirodne kozmetike",
    linkHref: "https://www.perfumariadaservas.shop",
  },
};